apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockchain-connector.fullname" . }}
  labels:
    {{- include "blockchain-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "blockchain-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
             {{ include "blockchain-connector.labels" . | nindent 8 }}
             {{- with .Values.deployment.additionalLabels }}
             {{- toYaml . | nindent 8 }}
             {{- end }}
         {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.enabled | quote }}
        prometheus.io/path: {{ .Values.prometheus.path }}
        prometheus.io/port: {{ .Values.prometheus.port }}
            {{- with .Values.deployment.additionalAnnotations }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: {{ include "blockchain-connector.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port}}
              protocol: TCP
            - name: http-health
              containerPort: {{ .Values.deployment.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://mkt-postgres:5432/mktdb
            - name: SPRING_R2DBC_USERNAME
              value: postgres
            - name: SPRING_R2DBC_PASSWORD
              value: postgres
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://mkt-postgres:5432/mktdb
            - name: LOGGING_LEVEL_ES_IN2_BLOCKCHAINCONNECTOR
              value: DEBUG
            - name: OPENAPI_SERVER_URL
              value: https://localhost:9091
            - name: OPENAPI_SERVER_DESCRIPTION
              value: Blockchain Connector Test Server
            - name: OPENAPI_INFO_TITLE
              value: Blockchain Connector
            - name: OPENAPI_INFO_DESCRIPTION
              value: Blockchain Connector Component
            - name: OPENAPI_INFO_VERSION
              value: 2.0.0-SNAPSHOT
            - name: OPENAPI_INFO_TERMS_OF_SERVICE
              value: https://example.com/terms
            - name: OPENAPI_INFO_LICENSE_NAME
              value: Apache 2.0
            - name: OPENAPI_INFO_LICENSE_URL
              value: https://www.apache.org/licenses/LICENSE-2.0.html
            - name: OPENAPI_INFO_CONTACT_NAME
              value: IN2, Ingeniería de la Información
            - name: OPENAPI_INFO_CONTACT_URL
              value: https://in2.es
            - name: OPENAPI_INFO_CONTACT_EMAIL
              value: contacto@in2.es
            - name: OPERATOR_ORGANIZATION_ID
              value: VATES-00869735
            - name: DLT_ADAPTER_DOMAIN
              value: http://dlt-adapter:8080
            - name: BLOCKCHAIN_RPC_ADDRESS
              value: https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6
            - name: BLOCKCHAIN_USER_ETHEREUM_ADDRESS
              value: 0xb794f5ea0ba39494ce839613fffba74279579268
            - name: BLOCKCHAIN_SUBSCRIPTION_ACTIVE
              value: "true"
            - name: BLOCKCHAIN_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: http://blockchain-connector:8080/notifications/dlt
            - name: BLOCKCHAIN_SUBSCRIPTION_EVENT_TYPES
              value: ProductOffering,ProductOrder
            - name: BROKER_EXTERNAL_DOMAIN
              value: https://example.com/scorpio
            - name: BROKER_INTERNAL_DOMAIN
              value: http://scorpio:9090
            - name: NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: http://blockchain-connector:8080/notifications/broker
            - name: NGSI_SUBSCRIPTION_ENTITY_TYPES
              value: ProductOffering,ProductOrder
            - name: BROKER_ADAPTER_DOMAIN
              value: http://broker-adapter:8080
            - name: BROKER_ADAPTER_PATHS_ENTITIES
              value: /api/v2/entities
            - name: BROKER_ADAPTER_PATHS_SUBSCRIPTIONS
              value: /api/v2/subscriptions
          resources:
                {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deployment.affinity }}
      affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deployment.tolerations }}
      tolerations:
             {{- toYaml . | nindent 8 }}
          {{- end }}
      restartPolicy: Always
