apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dome-wallet-keycloak.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dome-wallet-keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dome-wallet-keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dome-wallet-keycloak.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dome-wallet-keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{.Values.app.keycloak.admin}}
            - name: KC_HTTP_RELATIVE_PATH
              value: {{.Values.app.keycloak.relativePath}}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dome-wallet-keycloak.keycloakSecretName" . }}
                  key: {{ include "dome-wallet-keycloak.keycloak-passwordKey" . }}
            - name: KC_DB_USERNAME
              value: {{.Values.db.username}}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dome-wallet-keycloak.dbSecretName" . }}
                  key: {{ include "dome-wallet-keycloak.db-passwordKey" . }}
            - name: KC_DB
              value: {{.Values.db.type}}
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}{{ if not .Values.db.externalService }}:{{ .Values.db.port }}{{ end }}/{{ .Values.db.name }}"
            - name: KC_HOSTNAME_URL
              value: {{.Values.app.keycloak.hostnameUrl}}
            - name: KC_HOSTNAME_ADMIN_URL
              value: {{.Values.app.keycloak.adminUrl}}
            - name: SMTP_HOST
              value: {{ .Values.app.keycloak.mail.host }}
            - name: SMTP_PORT
              value: "{{ .Values.app.keycloak.mail.port }}" # Convert to string
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.mail-secretName" . }}
                  key: {{ include "keycloak.mail-userKey" . }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.mail-secretName" . }}
                  key: {{ include "keycloak.mail-passwordKey" . }}
            - name: SMTP_FROM
              value: "{{ .Values.app.keycloak.mail.from }}"
            - name: SMTP_FROM_DISPLAY_NAME
              value: "{{ .Values.app.keycloak.mail.fromDisplayName }}"
            - name: SMTP_REPLY_TO
              value: "{{ .Values.app.keycloak.mail.replyTo }}"
            - name: SMTP_AUTH
              value: "{{ .Values.app.keycloak.mail.properties.mail.smtp.auth }}" # Convert to string
            - name: SMTP_STARTTLS
              value: "{{ .Values.app.keycloak.mail.properties.mail.smtp.starttls.enable }}" # Convert to string
            - name: SMTP_SSL
              value: "{{ .Values.app.keycloak.mail.properties.mail.smtp.ssl.enable }}"