{{- if not .Values.db.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "wallet-api.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-db-password: {{ .Values.db.password | b64enc }}
  {{- end }}