{{- if not .Values.app.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallet-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "wallet-api.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-password: {{ .Values.app.keycloak.password | b64enc }}
  {{- end }}
