apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet-api.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "wallet-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.internalServerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "wallet-api.selectorLabels" . | nindent 4 }}
