{{- if not .Values.app.vault.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: wallet-api-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "wallet-api.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.app.vault.token | b64enc }}
  {{- end }}
