apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "verifier-api.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "verifier-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "verifier-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "verifier-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "verifier-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: SERVER_PORT
              value: {{ quote .Values.app.internalServerPort}}
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.app.profile}}
            - name: LOGGING_LEVEL_ES_IN2_VCVERIFIER
              value: {{.Values.app.logLevel.app}}
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: {{.Values.app.logLevel.security}}
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_OAUTH2
              value: {{.Values.app.logLevel.securityOauth2}}
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_FILTER
              value: {{.Values.app.logLevel.webFilter}}
            - name: SECURITY_AUTHORIZATION_SERVER
              value: {{ .Values.app.externalDomain }}
            - name: SECURITY_TOKEN_ACCESS_TOKEN_CRON_UNIT
              value: {{ .Values.app.accessToken.expirationUnitTime }}
            - name: SECURITY_TOKEN_ACCESS_TOKEN_EXPIRATION
              value: {{ quote .Values.app.accessToken.expirationTime}}
            - name: SECURITY_TOKEN_ID_TOKEN_CRON_UNIT
              value: {{ .Values.app.idToken.expirationUnitTime }}
            - name: SECURITY_TOKEN_ID_TOKEN_EXPIRATION
              value: {{ quote .Values.app.idToken.expirationTime}}
            - name: TRUST_FRAMEWORK_CLIENTS_REPOSITORY_URI
              value: {{ .Values.app.clientsRepository.uri}}
            - name: TRUST_FRAMEWORK_TRUSTED_ISSUER_LIST_URI
              value: {{ .Values.app.trustedIssuerList.uri}}
            - name: TRUST_FRAMEWORK_REVOCATION_LIST_URI
              value: {{ .Values.app.revocationList.uri}}
            - name: VERIFIER_UI_LOGIN_URIS_ONBOARDING_URI
              value: {{ .Values.app.verifierUiLoginUris.onboardingUri }}
            - name: VERIFIER_UI_LOGIN_URIS_SUPPORT_URI
              value: {{ .Values.app.verifierUiLoginUris.supportUri }}
            - name: VERIFIER_UI_LOGIN_URIS_WALLET_URI
              value: {{ .Values.app.verifierUiLoginUris.walletUri }}
            - name: SECURITY_LOGIN_CODE_EXPIRATION_PROPERTIES_CRON_UNIT
              value: {{ .Values.app.loginQrCode.expirationUnitTime }}
            - name: SECURITY_LOGIN_CODE_EXPIRATION_PROPERTIES_EXPIRATION
              value: {{ quote .Values.app.loginQrCode.expirationTime}}
            - name: VERIFIER_UI_CUSTOMIZATIONS_COLORS_PRIMARY
              value: {{ .Values.app.colors.primary | quote }}
            - name: VERIFIER_UI_CUSTOMIZATIONS_COLORS_PRIMARY_CONTRAST
              value: {{ .Values.app.colors.primaryContrast | quote }}
            - name: VERIFIER_UI_CUSTOMIZATIONS_COLORS_SECONDARY
              value: {{ .Values.app.colors.secondary | quote }}
            - name: VERIFIER_UI_CUSTOMIZATIONS_COLORS_SECONDARY_CONTRAST
              value: {{ .Values.app.colors.secondaryContrast | quote }}
            - name: VERIFIER_UI_CUSTOMIZATIONS_LOGO_SRC
              value: {{ .Values.app.logoSrc }}
            - name: VERIFIER_UI_CUSTOMIZATIONS_FAVICON_SRC
              value: {{ .Values.app.faviconSrc }}

            # PRIVATE KEY
            - name: CRYPTO_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "verifier-api.privateKey-secretName" . }}
                  key: {{ include "verifier-api.privateKey-privateKey" . }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}