apiVersion: v1
kind: Service
metadata:
  name: {{ include "verifier-api.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "verifier-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.internalServerPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "verifier-api.selectorLabels" . | nindent 4 }}
