{{- if not .Values.app.verifier.backend.security.serviceIdentity.verifiableCredential.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: verifiable-credential-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "verifier-api.labels" . | nindent 4 }}
type: Opaque
data:
  verifiableCredential: {{ .Values.app.verifier.backend.security.serviceIdentity.verifiableCredential.value | b64enc }}
{{- end }}