{{- if not .Values.app.verifier.backend.security.serviceIdentity.privateKey.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: verifier-api-private-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "verifier-api.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.app.verifier.backend.security.serviceIdentity.privateKey.value | b64enc }}
{{- end }}