apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wallet-ui.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    {{- include "wallet-ui.labels" . | nindent 4 }}
    io.kompose.service: wallet-ui
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wallet-ui.selectorLabels" . | nindent 6 }}
      io.kompose.service: wallet-ui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      {{- end }}
      labels:
        {{- include "wallet-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        io.kompose.network/kompose-default: "true"
        io.kompose.service: wallet-ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {}
          image: "{{ .Values.image.repository | default "in2workspace/wallet-ui"}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http 
              containerPort: 8088
              hostPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: WALLET_API_INTERNAL_DOMAIN
              value: {{.Values.app.walletApi.internalDomain}}
            - name: WALLET_API_WEBSOCKET_EXTERNAL_DOMAIN
              value: {{.Values.app.walletApi.websocketExternalDomain}}
            - name: WALLET_API_WEBSOCKET_PATH
              value: {{.Values.app.walletApi.websocketPath}}
            - name: WALLET_API_EXECUTE_CONTENT_PATH
              value: {{.Values.app.walletApi.executeContentPath}}
            - name: WALLET_API_REQUEST_CREDENTIAL_PATH
              value: {{.Values.app.walletApi.verifiablePresentationPath}}
            - name: WALLET_API_VERIFIABLE_PRESENTATION_PATH
              value: {{.Values.app.walletApi.credentialsPath}}
            - name: WALLET_API_CREDENTIALS_PATH
              value: {{.Values.app.walletApi.credentialsByIdPath}}
            - name: WALLET_API_CREDENTIALS_BY_ID_PATH
              value: {{.Values.app.walletApi.credentialsByIdPath}}
            - name: WALLET_API_REQUEST_SIGNED_CREDENTIAL_PATH
              value: {{.Values.app.walletApi.requestSignedCredentialPath}}
            - name: WALLET_API_CBOR_PATH
              value: {{.Values.app.walletApi.cborPath}}
            - name: IAM_EXTERNAL_DOMAIN
              value: {{.Values.app.iam.external_domain}}
            - name: IAM_REALM_PATH
              value: {{.Values.app.iam.realm_path}}
          resources:
            { { - toYaml .Values.resources | nindent 12 } }
              { { - with .Values.volumeMounts } }
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always