apiVersion: v2
name: wallet
description: Umbrella Helm chart for the Wallet
type: application
version: 1.2.0
appVersion: "v0.0.5"

dependencies:
  - name: wallet-api
    condition: wallet-api.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.1.1

  - name: dome-wallet-ui
    condition: dome-wallet-ui.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 0.1.5

  - name: dome-wallet-keycloak
    condition: dome-wallet-keycloak.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 0.1.3

  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.5

  - name: postgresql
    condition: wallet-postgresql.enabled
    alias: wallet-postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.5
