apiVersion: v2
name: wallet
description: Umbrella Helm chart for the Wallet
type: application
version: 1.0.3
appVersion: "v0.0.5"

dependencies:
  - name: wallet-api
    condition: wallet-api.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.0.2

  - name: dome-wallet-ui
    condition: dome-wallet-ui.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 0.1.4

  - name: dome-wallet-keycloak
    condition: dome-wallet-keycloak.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 0.1.3

  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5

  - name: scorpio-broker-aaio
    condition: scorpio.enabled
    alias: scorpio
    repository: https://fiware.github.io/helm-charts
    version: 0.4.9

  - name: postgresql
    condition: postgis.enabled
    alias: postgis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
