apiVersion: v2
name: wallet
description: Parent chart managing all the components of the Wallet application
type: application
# Chart version
version: 2.0.0
appVersion: "1.0.0"

dependencies:
  - name: wallet-backend
    version: "1.1.4"
    repository: https://in2workspace.github.io/helm-charts
    condition: wallet-backend.enabled

  - name: wallet-frontend
    version: "0.2.2"
    repository: https://in2workspace.github.io/helm-charts
    condition: wallet-frontend.enabled

  - name: wallet-postgres
    version: "16.4.5" # version could be consulted in https://artifacthub.io/packages/helm/bitnami/postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: wallet-postgres.enabled

  - name: keycloak-wallet
    version: "0.1.3"
    repository: https://in2workspace.github.io/helm-charts
    condition: keycloak-wallet.enabled

  - name: keycloak-wallet-postgres
    version: "16.4.5" # version could be consulted in https://artifacthub.io/packages/helm/bitnami/postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak-wallet-postgres.enabled




