apiVersion: v2
name: wallet
description: Umbrella Helm chart for DOME Wallet

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: blockchain-connector
    condition: blockchain-connector.enabled
    repository: https://dome-marketplace.github.io/access-node
    version: 0.1.0
  - name: broker-adapter
    condition: broker-adapter.enabled
    repository: https://dome-marketplace.github.io/access-node
    version: 0.1.0
  - name: dlt-adapter
    condition: dlt-adapter.enabled
    repository: https://dome-marketplace.github.io/access-node
    version: 1.0.3
  - name: kafka
    condition: kafka.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 26.0.0
  - name: postgresql
    condition: postgis.enabled
    alias: postgis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  - name: scorpio-broker-aaio
    condition: scorpio.enabled
    alias: scorpio
    repository: https://fiware.github.io/helm-charts
    version: 0.1.7
  - name: tm-forum-api
    condition: tm-forum-api.enabled
    repository: https://fiware.github.io/helm-charts
    version: 0.5.3
