global:
  tenantName: "in2"
  environment: "dev"
  # Se usa para construir el ingress.hosts.host: wallet.{{ tenantName }}.{{ externalDomain }}
  externalDomain: "127.0.0.1.nip.io"

# Wallet Backend subchart configuration
wallet-backend:
  # -- should be enabled?
  enabled: true
  # Image configuration
  image:
    pullPolicy: Allways
    tag: v1.4.1
  # Ingress specific configuration
  ingress:
    enabled: false
  # Application specific configuration
  app:
    logLevel: DEBUG

# Wallet Frontend subchart configuration
wallet-frontend:
  # -- should be enabled?
  enabled: true
  # Image configuration
  image:
    tag: v1.7.0
  # Ingress specific configuration
  ingress:
    enabled: false
  # Application specific configuration
  app:
    logsEnabled: false
    colors:
      primary: "#00ADD3"
      primaryContrast: "#ffffff"
      secondary: "#50c8ff"
      secondaryContrast: "#50c8ff"

# Wallet postgres subchart configuration
wallet-postgres:
  # -- should the postgresql deployment be enabled?
  enabled: false

## Keycloak subchart configuration
keycloak-wallet:
  # -- should be enabled?
  enabled: false

## Keycloak postgres subchart configuration
keycloak-wallet-postgres:
  # -- should the postgresql deployment be enabled?
  enabled: false

