global:
  # Tenant name
  tenantName: "in2"
  # current environments are: dev, test, prod
  environment: "dev"
  # Se usa para construir el ingress.hosts.host: wallet.{{ tenantName }}.{{ externalDomain }}
  externalDomain: "127.0.0.1.nip.io"
  # Ingress configuration
  ingress:
    enabled: true
    className: "nginx"
    sslRedirect: false
    backendProtocol: "HTTP"
    enableTLS: false
    clusterIssuer: "letsencrypt-in2-test-issuer"

# Wallet Backend subchart configuration
wallet-backend:
  # -- should be enabled?
  enabled: true
  # Image configuration
  image:
    # -- image pull policy
    pullPolicy: Always
    # -- image tag
    tag: v1.4.3-snapshot
  # Application specific configuration
  app:
    logLevel: DEBUG
    cors:
      allowedOrigins:
    db:
      existingSecret:
        # -- should an existing secret be used?
        enabled: true
        # -- name of the secret
        name: wallet-sealed-secret
        # -- key to retrieve the secret from
        key: postgres-password
    vault:
      existingSecret:
        # -- should an existing secret be used?
        enabled: true
        # -- name of the secret
        name: vault-unseal-secret
        # -- key to retrieve the secret from
        key: root

# Wallet Frontend subchart configuration
wallet-frontend:
  # -- should be enabled?
  enabled: true
  # Image configuration
  image:
    # -- image pull policy
    pullPolicy: Always
    # -- image tag
    tag: v1.7.0
  # Application specific configuration
  app:
    logsEnabled: false
    colors:
      primary: "#00ADD3"
      primaryContrast: "#ffffff"
      secondary: "#50c8ff"
      secondaryContrast: "#50c8ff"

# Wallet PostgreSQL subchart configuration
wallet-postgres:
  # -- should be enabled?
  enabled: false

## Keycloak subchart configuration
keycloak-wallet:
  # -- should be enabled?
  enabled: false

## Keycloak PostgreSQL subchart configuration
keycloak-wallet-postgres:
  # -- should be enabled?
  enabled: false

