apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  keycloakAdminPassword: {{ .Values.keycloak.admin.password | b64enc | quote }}
  keycloakTrustStorePassword: {{ .Values.keycloak.https.trustStorePassword | b64enc | quote }}
  keycloakDbPassword: {{ .Values.keycloak.db.password | b64enc | quote }}
