apiVersion: v1
kind: Service
metadata:
  name: {{ include "issuer-keycloak-plugin.fullname" . }}
  labels:
    {{- include "issuer-keycloak-plugin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "issuer-keycloak-plugin.selectorLabels" . | nindent 4 }}