# Default values for wallet-driving-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: in2kizuna/wallet-driving-application
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 4200

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
app:
  # wallet-server API
  server:
    url: http://localhost:8080
  # wallet-identity-provider (Keycloak)
  iam:
    url: http://localhost:9099
    uri: /realms/wallet
  executionContext:
    uri: /api/v2/execute-content
  verifiablePresentation:
    uri: /api/v2/verifiable-presentation
  credentials:
    uri: /api/v2/credentials
  credentialsId:
    uri: /api/v2/credentials?credentialId=
  user:
    uri: /api/v2/users
  # wallet-server Websocket
  websocket:
    url: ws://localhost:8080
    uri: /api/v2/pin
