{{- if not .Values.db.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "issuer-api.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc }}
{{- end }}