apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "issuer-api.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "issuer-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "issuer-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "issuer-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "issuer-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.profile }}
            - name: LOGGING_LEVEL_ROOT
              value: {{ .Values.app.logLevel }}
            - name: SPRING_WEBFLUX_BASEPATH
              value: {{ .Values.app.basePath }}
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://{{ .Values.db.host }}{{ if not .Values.db.externalService }}:{{ .Values.db.port }}{{ end }}/{{ .Values.db.name }}"
            - name: SPRING_R2DBC_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.db-secretName" . }}
                  key: {{ include "issuer-api.db-passwordKey" . }}
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}{{ if not .Values.db.externalService }}:{{ .Values.db.port }}{{ end }}/{{ .Values.db.name }}"
            - name: SPRING_MAIL_HOST
              value: {{ .Values.app.mail.host }}
            - name: SPRING_MAIL_PORT
              value: "{{ .Values.app.mail.port }}" # Convert to string
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.mail-secretName" . }}
                  key: {{ include "issuer-api.mail-userKey" . }}
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.mail-secretName" . }}
                  key: {{ include "issuer-api.mail-passwordKey" . }}
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "{{ .Values.app.mail.properties.mail.smtp.auth }}" # Convert to string
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "{{ .Values.app.mail.properties.mail.smtp.starttls.enable }}" # Convert to string
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST
              value: {{ .Values.app.mail.properties.mail.smtp.ssl.trust }}
            - name: API_EXTERNAL_DOMAIN
              value: "{{ .Values.app.api.externalDomain.scheme }}://{{ .Values.app.api.externalDomain.host }}{{ if not .Values.app.api.externalDomain.externalService }}:{{ .Values.app.api.externalDomain.internalPort }}{{ end }}{{ .Values.app.api.externalDomain.path }}"
            - name: API_INTERNAL_DOMAIN
              value: {{ .Values.app.api.internalDomain }}
            - name: API_CONFIG_SOURCE
              value: {{ .Values.app.api.configSource }}
            - name: API_CACHE_LIFETIME_CREDENTIAL_OFFER
              value: "{{ .Values.app.api.cacheLifetimeCredentialOffer }}" # Convert to string
            - name: API_CACHE_LIFETIME_VERIFIABLE_CREDENTIAL
              value: "{{ .Values.app.api.cacheLifetimeVerifiableCredential }}" # Convert to string
            - name: AUTH_SERVER_PROVIDER
              value: {{ .Values.app.authServer.provider }}
            - name: AUTH_SERVER_EXTERNAL_DOMAIN
              value: "{{ .Values.app.authServer.externalDomain.scheme }}://{{ .Values.app.authServer.externalDomain.host }}{{ if not .Values.app.authServer.externalDomain.externalService }}:{{ .Values.app.authServer.externalDomain.internalPort }}{{ end }}{{ .Values.app.authServer.externalDomain.path }}"
            - name: AUTH_SERVER_INTERNAL_DOMAIN
              value: {{ .Values.app.authServer.internalDomain }}
            - name: AUTH_SERVER_REALM
              value: {{ .Values.app.authServer.realm }}
            - name: AUTH_SERVER_CLIENT_CLIENT_ID
              value: {{ .Values.app.authServer.client.clientId }}
            - name: AUTH_SERVER_CLIENT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.authServerClient-secretName" . }}
                  key: {{ include "issuer-api.authServerClient-clientSecretKey" . }}
            - name: AUTH_SERVER_PATHS_TOKEN_PATH
              value: {{ .Values.app.authServer.paths.tokenPath }}
            - name: AUTH_SERVER_CLIENT_USERNAME
              value: {{ .Values.app.authServer.client.username }}
            - name: AUTH_SERVER_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.authServerClient-secretName" . }}
                  key: {{ include "issuer-api.authServerClient-passwordKey" . }}
            - name: ISSUER_UI_EXTERNAL_DOMAIN
              value: "{{ .Values.app.ui.externalDomain.scheme }}://{{ .Values.app.ui.externalDomain.host }}{{ if not .Values.app.ui.externalDomain.externalService }}:{{ .Values.app.ui.externalDomain.internalPort }}{{ end }}{{ .Values.app.ui.externalDomain.path }}"
            - name: ISSUER_UI_INTERNAL_DOMAIN
              value: {{ .Values.app.ui.internalDomain }}
            - name: REMOTE_SIGNATURE_INTERNAL_DOMAIN
              value: {{ .Values.app.remoteSignature.internalDomain }}
            - name: REMOTE_SIGNATURE_EXTERNAL_DOMAIN
              value: "{{ .Values.app.remoteSignature.externalDomain.scheme }}://{{ .Values.app.remoteSignature.externalDomain.host }}{{ if not .Values.app.remoteSignature.externalDomain.externalService }}:{{ .Values.app.remoteSignature.externalDomain.internalPort }}{{ end }}{{ .Values.app.remoteSignature.externalDomain.path }}"
            - name: WALLET_URL
              value: {{ .Values.app.wallet.url }}
            - name: DEFAULT_SIGNER_COMMON_NAME
              value: {{ .Values.app.defaultSigner.commonName }}
            - name: DEFAULT_SIGNER_COUNTRY
              value: {{ .Values.app.defaultSigner.country }}
            - name: DEFAULT_SIGNER_EMAIL
              value: {{ .Values.app.defaultSigner.email }}
            - name: DEFAULT_SIGNER_ORGANIZATION_IDENTIFIER
              value: {{ .Values.app.defaultSigner.organizationIdentifier }}
            - name: DEFAULT_SIGNER_ORGANIZATION
              value: {{ .Values.app.defaultSigner.organization }}
            - name: DEFAULT_SIGNER_SERIAL_NUMBER
              value: {{ .Values.app.defaultSigner.serialNumber }}
            - name: VERIFIER_VERIFIER_DID_KEY
              value: {{ .Values.app.verifier.verifierDidKey }}
            - name: VERIFIER_EXTERNAL_DOMAIN
              value: {{ .Values.app.verifier.externalDomain }}
            - name: VERIFIER_CREDENTIAL_SUBJECT_KEY
              value: {{ .Values.app.verifier.credentialSubjectKey }}
            - name: VERIFIER_VC
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.verifier-secretName" . }}
                  key: {{ include "issuer-api.verifier-vcKey" . }}
            - name: VERIFIER_CRYPTO_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "issuer-api.verifier-secretName" . }}
                  key: {{ include "issuer-api.verifier-cryptoPrivateKey" . }}
            - name: VERIFIER_CLIENT_ASSERTION_TOKEN_CRON_UNIT
              value: {{ .Values.app.verifier.clientAssertion.token.cronUnit }}
            - name: VERIFIER_CLIENT_ASSERTION_TOKEN_EXPIRATION
              value: "{{ .Values.app.verifier.clientAssertion.token.expiration }}" # Convert to string
