{{- if not .Values.app.remoteSignature.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: issuer-api-remote-signature-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "issuer-api.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.app.remoteSignature.credentialId | b64enc }}
  client-secret: {{ .Values.app.remoteSignature.clientSecret | b64enc }}
  credential-id: {{ .Values.app.remoteSignature.credentialId | b64enc }}
  credential-password: {{ .Values.app.remoteSignature.credentialPassword | b64enc }}
{{- end }}