{{- if not .Values.db.existingSecret.enabled -}}
{{- if not .Values.app.authServer.client.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: issuer-api-secrets
type: Opaque
data:
  dbPassword: {{ .Values.db.password | b64enc | quote }}
  authServerClientSecret: {{ .Values.app.authServer.client.clientSecret | b64enc | quote }}
  authServerClientPassword: {{ .Values.app.authServer.client.password | b64enc | quote }}

