{{- if not .Values.app.verifier.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: issuer-api-verifier-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "issuer-api.labels" . | nindent 4 }}
type: Opaque
data:
  vc: {{ .Values.app.verifier.vc | b64enc }}
  private-key: {{ .Values.app.verifier.crypto.privateKey | b64enc }}
{{- end }}