apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "broker-adapter.fullname" . }}
  labels:
    {{- include "broker-adapter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "broker-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
          {{ include "broker-adapter.labels" . | nindent 8 }}
          {{- with .Values.deployment.additionalLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.enabled | quote }}
        prometheus.io/path: {{ .Values.prometheus.path }}
        prometheus.io/port: {{ .Values.prometheus.port }}
              {{- with .Values.deployment.additionalAnnotations }}
              {{- toYaml . | nindent 8 }}
              {{- end }}
          {{- end }}
    spec:
      serviceAccountName: {{ include "broker-adapter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port}}
              protocol: TCP
            - name: http-health
              containerPort: {{ .Values.deployment.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: LOGGING_LEVEL_ES_IN2_BROKERADAPTER
              value: DEBUG
            - name: BROKER_EXTERNAL_DOMAIN
              value: https://example.com/scorpio
            - name: BROKER_INTERNAL_DOMAIN
              value: http://scorpio:9090
            - name: BROKER_PATHS_ENTITIES
              value: /ngsi-ld/v1/entities
            - name: BROKER_PATHS_SUBSCRIPTIONS
              value: /ngsi-ld/v1/subscriptions
          resources:
                {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deployment.affinity }}
      affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deployment.tolerations }}
      tolerations:
             {{- toYaml . | nindent 8 }}
          {{- end }}
      restartPolicy: Always
