{{- if or
    (not .Values.app.db.existingSecret.enabled)
    (not .Values.spring.mail.existingSecret.enabled)
    (not (index .Values "adapter-identity" "existingSecret" "enabled")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dome-adapter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dome-adapter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.app.db.existingSecret.enabled }}
  postgres-password: {{ .Values.app.db.password | b64enc | quote }}
  {{- end }}

  {{- if not .Values.spring.mail.existingSecret.enabled }}
  mail-username: {{ .Values.spring.mail.username | b64enc | quote }}
  mail-password: {{ .Values.spring.mail.password | b64enc | quote }}
  {{- end }}

  {{- if not (index .Values "adapter-identity" "existingSecret" "enabled") }}
  adapter-identity-credential-subject-did-key: {{ index .Values "adapter-identity" "credential-subject-did-key" | b64enc | quote }}
  adapter-identity-jwt-credential: {{ index .Values "adapter-identity" "jwt-credential" | b64enc | quote }}
  adapter-identity-private-key: {{ index .Values "adapter-identity" "crypto" "private-key" | b64enc | quote }}
  {{- end }}
  {{- end }}