{{- if or (not .Values.spring.r2dbc.existingSecret.enabled) (not .Values.spring.mail.existingSecret.enabled) (not (index .Values "adapter-identity" "existingSecret" "enabled")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dome-adapter.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not .Values.spring.r2dbc.existingSecret.enabled }}
  {{ .Values.spring.r2dbc.secretKeys.username }}: {{ required "spring.r2dbc.username is required when spring.r2dbc.existingSecret.enabled=false" .Values.spring.r2dbc.username | b64enc | quote }}
  {{ .Values.spring.r2dbc.secretKeys.password }}: {{ required "spring.r2dbc.password is required when spring.r2dbc.existingSecret.enabled=false" .Values.spring.r2dbc.password | b64enc | quote }}
{{- end }}

{{- if not .Values.spring.mail.existingSecret.enabled }}
  {{ .Values.spring.mail.existingSecret.username }}: {{ .Values.spring.mail.username | b64enc | quote }}
  {{ .Values.spring.mail.existingSecret.password }}: {{ .Values.spring.mail.password | b64enc | quote }}
{{- end }}

{{- if not (index .Values "adapter-identity" "existingSecret" "enabled") }}
  {{ index .Values "adapter-identity" "existingSecret" "jwtCredential" }}: {{ index .Values "adapter-identity" "jwt-credential" | b64enc | quote }}
  {{ index .Values "adapter-identity" "existingSecret" "privateKey" }}: {{ index .Values "adapter-identity" "crypto" "private-key" | b64enc | quote }}
  {{- end }}
{{- end }}