apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dome-issuer-keycloak.fullname" . }}-config
  namespace: {{ $.Release.Namespace | quote }}
data:
  localhost-crt.pem: |-
{{ $.Files.Get "files/localhost-crt.pem" | indent 4 }}
  localhost-key.pem: |-
{{ $.Files.Get "files/localhost-key.pem" | indent 4 }}
  truststore.jks: |-
{{ $.Files.Get "files/truststore.jks" | indent 4 }}
