apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dome-issuer-keycloak.fullname" . }}-config
data:
  localhost-crt.pem: |-
    {{ .Files.Get "files/localhost-crt.pem" | nindent 4 }}
  localhost-key.pem: |-
    {{ .Files.Get "files/localhost-key.pem" | nindent 4 }}
