apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dome-issuer-keycloak.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dome-issuer-keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dome-issuer-keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dome-issuer-keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dome-issuer-keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: certificate-init
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              #!/bin/sh

              # Install required packages
              apk add --no-cache curl openjdk11-jre openssl

              # Create a temporal storage
              echo "Creating temporal storage..."
              mkdir -p /opt/keycloak/conf/tmp
              cd /opt/keycloak/conf/tmp

              # Delete previous data: truststore, certificates and eu-lotl.xml
              echo "Deleting previous data: truststore, certificates and eu-lotl.xml"
              rm -f cert_* truststore.jks eu-lotl.xml

              # Create an empty truststore.jks if it doesn't exist
              if [ ! -f /opt/keycloak/conf/truststore.jks ]; then
                echo "Creating an empty truststore.jks"
                keytool -genkey -alias tempkey -keystore /opt/keycloak/conf/truststore.jks -storepass pempas -keypass pempas -dname "CN=Temp, OU=Temp, O=Temp, L=Temp, ST=Temp, C=US"
                keytool -delete -alias tempkey -keystore /opt/keycloak/conf/truststore.jks -storepass pempas
              fi

              # Download eu-lotl.xml file
              echo "Downloading eu-lotl.xml file..."
              curl -s https://sedediatid.mineco.gob.es/Prestadores/TSL/TSL.xml -o eu-lotl.xml

              if [ $? -ne 0 ]; then
                echo "Error downloading eu-lotl.xml file."
                exit 1
              fi

              # Validate that the file was downloaded successfully
              if [ ! -f eu-lotl.xml ]; then
                echo "eu-lotl.xml not found after download."
                exit 1
              fi

              echo "eu-lotl.xml downloaded successfully."

              # Extract certificates from eu-lotl.xml
              certificates=$(grep -o '<X509Certificate>[^<]*</X509Certificate>' eu-lotl.xml | sed -e 's/<X509Certificate>//g' -e 's/<\/X509Certificate>//g')
              count=1

              for certificate in $certificates; do
                file="cert_$count.pem"

                if [ -s "$file" ]; then
                  echo "$file does exist."
                else
                  echo "-----BEGIN CERTIFICATE-----
                  $certificate
                    -----END CERTIFICATE-----" > "$file"
                fi

                # Validate that the PEM file was created successfully
                if [ ! -f "$file" ]; then
                  echo "Failed to create $file"
                  exit 1
                fi

                # Validate that the PEM file is not empty
                echo "Content of $file:"
                cat "$file"

                # Generate a DER file from the PEM file
                openssl x509 -in "$file" -out "cert_$count.der" -outform DER

                # Validate that the DER file was created successfully
                if [ ! -f "cert_$count.der" ]; then
                  echo "Failed to create cert_$count.der"
                  exit 1
                fi

                # Import the DER file to the truststore
                echo "yes" | keytool -import -alias "cert_$count" -file "cert_$count.der" -keystore /opt/keycloak/conf/truststore.jks -storepass pempas

                if [ $? -ne 0 ]; then
                  echo "Failed to import cert_$count.der to truststore.jks"
                  exit 1
                fi

                count=$((count + 1))
              done

              echo "Certificates imported to truststore."

              # List the content of the truststore
              echo "Truststore content:"
              keytool -list -keystore /opt/keycloak/conf/truststore.jks -storepass pempas

              # Clean up temporary files
              echo "Cleaning up temporary files."
              rm -f cert_* eu-lotl.xml

              echo "Cleanup completed."
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.admin.username }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.secretName.admin" . }}
                  key: {{ include "keycloak.passwordKey.admin" . }}
            - name: KC_HOSTNAME_URL
              value: {{ .Values.keycloak.hostname.url }}
            - name: KC_HOSTNAME_ADMIN_URL
              value: {{ .Values.keycloak.hostname.adminUrl }}
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: {{ .Values.keycloak.https.certificateKeyFile }}
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: {{ .Values.keycloak.https.certificateFile }}
            - name: KC_HTTPS_TRUST_STORE_FILE
              value: {{ .Values.keycloak.https.trustStoreFile }}
            - name: KC_HTTPS_TRUST_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.secretName.https" . }}
                  key: {{ include "keycloak.trustStorePasswordKey.https" . }}
            - name: KC_HTTPS_CLIENT_AUTH
              value: {{ .Values.keycloak.https.clientAuth }}
            - name: KC_DB
              value: {{ .Values.keycloak.db.type }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.db.username }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.secretName.db" . }}
                  key: {{ include "keycloak.passwordKey.db" . }}
            - name: KC_DB_URL
              value: {{ .Values.keycloak.db.url }}
            - name: DB_PORT
              value: "{{ .Values.keycloak.db.port }}"
            - name: ISSUER_API_URL
              value: {{ .Values.issuerApi.url }}
            - name: ISSUER_API_EXTERNAL_URL
              value: {{ .Values.issuerApi.externalUrl }}
            - name: PRE_AUTH_LIFESPAN
              value: "{{ .Values.preAuth.lifespan }}"
            - name: PRE_AUTH_LIFESPAN_TIME_UNIT
              value: {{ .Values.preAuth.lifespanTimeUnit }}
            - name: TX_CODE_SIZE
              value: "{{ .Values.txCode.size }}"
            - name: TX_CODE_DESCRIPTION
              value: {{ .Values.txCode.description }}
            - name: TOKEN_EXPIRATION
              value: "{{ .Values.token.expiration }}"
          volumeMounts:
            - name: truststore-volume
              mountPath: /opt/keycloak/conf
      volumes:
        - name: truststore-volume
          persistentVolumeClaim:
            claimName: truststore-pvc
        - name: server-key
          configMap:
            name: {{ include "dome-issuer-keycloak.fullname" . }}-config
            items:
              - key: localhost-key.pem
                path: server.key.pem
        - name: server-crt
          configMap:
            name: {{ include "dome-issuer-keycloak.fullname" . }}-config
            items:
              - key: localhost-crt.pem
                path: server.crt.pem
