{{- if not .Values.keycloak.https.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: trust-store-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-issuer-keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  trust-store-password: {{ .Values.keycloak.https.trustStorePassword | b64enc }}
{{- end }}