apiVersion: v2
name: issuer
description: Umbrella Helm chart for the issuer

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.15

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v1.0.3"

dependencies:
  - name: issuer-api
    alias: issuer-api
    condition: issuer-api.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.0.4

  - name: issuer-ui
    alias: issuer-ui
    condition: issuer-ui.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.0.1
  
  - name: dome-issuer-keycloak
    alias: dome-issuer-keycloak
    condition: dome-issuer-keycloak.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.0.8

  - name: postgresql
    condition: issuer-postgres.enabled
    alias: issuer-postgres
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  
  - name: postgresql
    condition: issuer-postgres.enabled
    alias: issuer-keycloak-postgres
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5
  