{{- if or
    (not .Values.app.db.existingSecret.enabled)
    (not .Values.app.ebsiTest.client.existingSecret.enabled)
    (not .Values.app.ebsiTest.userData.existingSecret.enabled)
    (not .Values.app.vault.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dome-wallet-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-wallet-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.app.db.existingSecret.enabled }}
  postgres-password: {{ .Values.app.db.password | b64enc }}
  {{- end }}
  {{- if not .Values.app.ebsiTest.client.existingSecret.enabled }}
  ebsi-client-secret: {{ .Values.app.ebsiTest.client.secret | b64enc }}
  {{- end }}
  {{- if not .Values.app.ebsiTest.userData.existingSecret.enabled }}
  ebsi-user-password: {{ .Values.app.ebsiTest.userData.password | b64enc }}
  {{- end }}
  {{- if not .Values.app.vault.existingSecret.enabled }}
  vault-token: {{ .Values.app.vault.token | b64enc }}
  {{- end }}
{{- end }}
