{{- if not .Values.app.defaultSigner.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: issuer-api-default-signer-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-issuer-api.labels" . | nindent 4 }}
type: Opaque
data:
  common-name: {{ .Values.app.defaultSigner.commonName | b64enc }}
  country: {{ .Values.app.defaultSigner.country | b64enc }}
  email: {{ .Values.app.defaultSigner.email | b64enc }}
  organization: {{ .Values.app.defaultSigner.organization | b64enc }}
  organization-identifier: {{ .Values.app.defaultSigner.organizationIdentifier | b64enc }}
  serial-number: {{ .Values.app.defaultSigner.serialNumber | b64enc }}
{{- end }}