{{- if not .Values.app.issuerIdentity.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: issuer-api-issuer-identity-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-issuer-api.labels" . | nindent 4 }}
type: Opaque
data:
  vc: {{ .Values.app.issuerIdentity.vcJwt | b64enc }}
  private-key: {{ .Values.app.issuerIdentity.privateKey | b64enc }}
  credential-did-key: {{ .Values.app.issuerIdentity.credentialDidKey | b64enc }}
{{- end }}