apiVersion: v1
kind: Service
metadata:
  name: {{ include "dome-issuer-api.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dome-issuer-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.internalServerPort }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: 30001
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "dome-issuer-api.selectorLabels" . | nindent 4 }}