apiVersion: v2
name: dome-wallet
description: Helm chart for the Wallet
type: application
version: 1.4.3
appVersion: "v0.0.5"

dependencies:
  - name: dome-wallet-backend
    version: 1.2.1
    condition: dome-wallet-backend.enabled

  - name: dome-wallet-frontend
    condition: dome-wallet-frontend.enabled
    version: 0.4.0

  - name: postgresql
    alias: dome-wallet-postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.5
    condition: dome-wallet-postgresql.enabled

  - name: dome-wallet-keycloak
    version: 0.1.4
    condition: dome-wallet-keycloak.enabled

  - name: postgresql
    alias: dome-wallet-keycloak-postgresql
    version: 16.4.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: dome-wallet-keycloak-postgresql.enabled
