apiVersion: v2
name: dome-wallet
description: Helm chart for the Wallet
type: application
version: 1.3.18
appVersion: "v0.0.5"

dependencies:
  - name: dome-wallet-api
    condition: dome-wallet-api.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 1.1.7

  - name: dome-wallet-ui
    condition: dome-wallet-ui.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 0.3.2

  - name: postgresql
    condition: dome-wallet-postgresql.enabled
    alias: dome-wallet-postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.5

  - name: dome-wallet-keycloak
    condition: dome-wallet-keycloak.enabled
    repository: https://in2workspace.github.io/helm-charts
    version: 0.1.3

  - name: postgresql
    condition: dome-wallet-keycloak-postgresql.enabled
    alias: dome-wallet-keycloak-postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.5
