fullNameOverride: ""
nameOverride: ""

# Ingress configuration
ingress:
  enabled: true
  labels:
  className: "nginx"
  sslRedirect: false
  backendProtocol: "HTTP"
  enableTLS: false
  clusterIssuer: "letsencrypt-in2-test-issuer"
  host: "example-host"

## configuration for the dome-wallet-backend
dome-wallet-backend:
  # -- should be enabled?
  enabled: true
  fullnameOverride: "dome-wallet-backend"
  image:
    # -- image pull policy
    pullPolicy: Always
    # -- image tag
    tag: v1.4.3
  # ingress specific configuration
  ingress:
    enabled: false
  ## deployment specific configuration
  app:
    # has to match ingress backend path
    # todo: remove or refactor to match it with ingress backend path
    basePath: "/api"
    logLevel: DEBUG
    authServer:
      externalUrl: http://www.example-external-domain.org/keycloak/realms/wallet
      internalUrl: http://www.example-internal-domain.org/keycloak/realms/wallet
    cors:
      # expects a string of url's separated with comma and space
      allowedOrigins: "www.example-cors.com, www.example-cors-two.com"
    vault:
      provider: hashicorp
      url: http://vault-server:8200
      token: defaultToken
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: dome-wallet-sealed-secret
        # -- key to retrieve the token from
        key: token
    ebsiTest:
      url: http://dome-wallet-keycloak:8080/realms/wallet/protocol/openid-connect/token
      client:
        id: user-registry-client
        secret: defaultSecret
        existingSecret:
          # -- should an existing secret be used
          enabled: false
          # -- name of the secret
          name: dome-wallet-sealed-secret
          # -- key to retrieve the password from
          key: client-secret
      userData:
        name: admin
        password: defaultPassword
        existingSecret:
          # -- should an existing secret be used
          enabled: false
          # -- name of the secret
          name: dome-wallet-sealed-secret
          # -- key to retrieve the password from
          key: user-password
    db:
      schema: wallet
      host: dome-wallet-postgres
      port: 5432
      name: wallet
      username: postgres
      password: postgres
      existingSecret:
        enabled: false
        name: dome-wallet-sealed-secret
        key: password

## configuration for the dome-wallet-frontend
dome-wallet-frontend:
  # -- should be enabled?
  enabled: true
  fullnameOverride: "dome-wallet-frontend"
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: v1.9.0
  ## ingress specific configuration
  ingress:
    enabled: false
  ## deployment specific configuration
  app:
    logsEnabled: false
    colors:
      primary: "#00ADD3"
      primaryContrast: "#ffffff"
      secondary: "#50c8ff"
      secondaryContrast: "#50c8ff"
    logoSrc: "assets/logos/no-image.png"
    faviconSrc: "assets/icons/dome-favicon.png"
    # path has to match backend basePath
    walletApi:
      internalDomain: https://example-internal-domain.org/api
      websocketExternalDomain: wss://example-external-domain/api
    iam:
      externalUrl: https://example-external-domain.org/keycloak/realms/wallet

## configuration for the dome-wallet-keycloak
# todo: will be disabled when there is centralized keycloak
dome-wallet-keycloak:
  # -- should be enabled?
  enabled: false
  ## ingress specific configuration
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-in2-test-issuer
    hosts:
      - host: wallet.dome-marketplace-lcl.org
        paths:
          - path: /keycloak
            pathType: Prefix
    tls:
      - hosts:
          - wallet.dome-marketplace-lcl.org
        secretName: wallet-tls-secret
  ## deployment specific configuration
  app:
    internalServerPort: 8080
    keycloak:
      hostnameUrl: "http://dome-wallet-keycloak/keycloak"
      adminUrl: "http://dome-wallet-keycloak/keycloak"
      relativePath: /keycloak
      admin: admin
      password: admin
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: dome-wallet-sealed-secret
        # -- key to retrieve the password from
        key: keycloak-password
      mail:
        host: smtp.example.org
        port: 587
        from: example@example.org
        fromDisplayName: Example
        replyTo: example@example.org
        username: user
        password: password
        existingSecret:
          enabled: false
          name: mail-secret
          userKey: mail-user
          passwordKey: mail-password
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              ssl:
                enable: false
  db:
    type: postgres
    host: dome-wallet-keycloak-postgres
    port: 5432
    externalService: false
    name: keycloak
    username: postgres
    password: postgres
    existingSecret:
      # -- should an existing secret be used
      enabled: false
      # -- name of the secret
      name: dome-wallet-secret
      # -- key to retrieve the password from
      key: keycloak-db-password

## configuration of postgres to be used for the blockchain-connector - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
# todo: will be disabled when there is centralized keycloak
dome-wallet-keycloak-postgresql:
  # -- should the postgresql deployment be enabled
  enabled: true
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  fullnameOverride: dome-wallet-keycloak-postgres
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  nameOverride: dome-wallet-keycloak-postgres
  ## network policy configuration
  networkPolicy:
    enabled: false
  ## persistence volume claim configuration retention policy
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Retain
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
  ## configuration of the postgres primary replica
  primary:
    # Configuration for Velero backup
    annotations:
      backup.velero.io/backup-volumes: data
    podAnnotations:
      backup.velero.io/backup-volumes: data
    ## provide db initialization

## configuration of postgres
# todo: will be disabled when there is centralized database
dome-wallet-postgresql:
  # -- should the postgresql deployment be enabled
  enabled: true
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # todo dome-wallet-postgres?
  fullnameOverride: wallet-postgres
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # todo dome-wallet-postgres?
  nameOverride: wallet-postgres
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
    # -- database name to be used
    database: wallet
  ## configuration of the postgres primary replica
  primary:
    ## network policy configuration
    networkPolicy:
      enabled: false
    ## persistence volume claim configuration retention policy
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Retain