apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dome-wallet-ui.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dome-wallet-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dome-wallet-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dome-wallet-ui.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dome-wallet-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: LOGS_ENABLED
              value: {{ quote .Values.app.logsEnabled }}
            - name: PRIMARY
              value: {{ .Values.app.colors.primary | quote }}
            - name: PRIMARY_CONTRAST
              value: {{ .Values.app.colors.primaryContrast | quote }}
            - name: SECONDARY
              value: {{ .Values.app.colors.secondary | quote }}
            - name: SECONDARY_CONTRAST
              value: {{ .Values.app.colors.secondaryContrast | quote }}
            - name: LOGO_SRC
              value: {{ .Values.app.logoSrc }}
            - name: FAVICON_SRC
              value: {{ .Values.app.faviconSrc }}
            - name: WALLET_API_INTERNAL_DOMAIN
              value: {{.Values.app.walletApi.internalDomain}}
            - name: WALLET_API_WEBSOCKET_EXTERNAL_DOMAIN
              value: {{.Values.app.walletApi.websocketExternalDomain}}
            - name: IAM_EXTERNAL_DOMAIN
              value: {{.Values.app.iam.external_domain}}
            - name: IAM_REALM_PATH
              value: {{.Values.app.iam.realm_path}}