{{- if .Values.velero.schedule.enabled -}}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "app-example-chart.fullname" . }}-backup
  namespace: velero # Los Schedules deben crearse en el namespace de Velero
  labels:
    {{- include "app-example-chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.velero.schedule.cron | quote }}
  template:
    labelSelector:
      matchLabels:
        {{- include "app-example-chart.selectorLabels" . | nindent 8 }}
    includeNamespaces:
      - {{ .Release.Namespace }}
    snapshotVolumes: true
    ttl: {{ .Values.velero.schedule.ttl }}
{{- end }}