{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "issuer.fullname" . }}
  labels:
    {{- include "issuer-backend.labels" . | nindent 4 }}
    {{- include "issuer-frontend.labels" . | nindent 4 }}
    {{- include "dss.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.global.ingress.sslRedirect }}"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ .Values.global.ingress.backendProtocol }}"
    {{- if .Values.global.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ include "issuer.application.domain" . }}
      http:
        paths:
          # Backend
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: {{ include "issuer-backend.service.name" . }}
                port:
                  number: 80
          # Frontend
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "issuer-frontend.service.name" . }}
                port:
                  number: 80
          # Digital Signature Service
          - path: "/dss"
            pathType: Prefix
            backend:
              service:
                name: {{ include "issuer-dss.service.name" . }}
                port:
                  number: 80
  {{- if .Values.global.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ include "issuer.application.domain" . }}
      secretName: wallet-tls-secret
  {{- end }}
{{- end }}
