apiVersion: v1
kind: Secret
metadata:
  name: issuer-secret
  namespace: {{ .Release.Namespace }}
data:
  #database
  postgres-password: cG9zdGdyZXM=
  #service-identity
  private-key: ""
  did-key: ""
  vc: ""
  # keycloak
  keycloak-client-secret: ""
  keycloak-user-password: ""
  # email
  email-username: ""
  email-password: ""
  # remote-signature
  client-id: ""
  client-secret: ""
  credential-id: ""
  credential-password: ""
  # signer
  signer-common-name: ""
  signer-serial-number: ""
  signer-email: ""
  signer-organization: ""
  signer-organization-identifier: ""
  signer-country: ""
  # dss
  certificate-password: ""
