apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-cm
  labels:
    {{- include "wallet-backend.labels" . | nindent 4 }}
data:
  TENANT_NAME: "{{ .Values.global.tenantName }}"
  ENVIRONMENT: "{{ .Values.global.environment }}"
  KEYCLOAK_EXTERNAL_DOMAIN: "{{ include "keycloak.domain" . | trim }}"
  KEYCLOAK_REALM_PATH: "/realms/{{ .Values.global.tenantName }}-wallet"
  DB_HOST: "tenant-{{ .Values.global.tenantName | lower }}-postgres"
  DB_NAME: "{{ .Values.global.tenantName }}"
  DB_URL: "r2dbc:postgresql://tenant-{{ .Values.global.tenantName | lower }}-postgresql:{{ .Values.app.db.port | default 5432 }}/{{ .Values.global.tenantName }}?schema=wallet"
  FLYWAY_URL: "jdbc:postgresql://tenant-{{ .Values.global.tenantName | lower }}-postgresql:{{ .Values.app.db.port | default 5432 }}/{{ .Values.global.tenantName }}?schema=wallet"