{{- if not .Values.app.ebsiTest.userData.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: wallet-api-user-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "wallet-api.labels" . | nindent 4 }}
type: Opaque
data:
  user-password: {{ .Values.app.ebsiTest.userData.password | b64enc }}
  {{- end }}