{{- if not .Values.db.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: wallet-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "wallet-api.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.app.db.password | b64enc }}
  ebsi-client-secret: {{ .Values.app.ebsiTest.client.secret | b64enc }}
  ebsi-user-password: {{ .Values.app.ebsiTest.userData.password | b64enc }}
  vault-token: {{ .Values.app.vault.token | b64enc }}
{{- end }}