apiVersion: v1
kind: Secret
metadata:
  name: tenant-leviathan-wallet-sealed-secret
  namespace: tenant-leviathan
data:
  postgres-password: "" # base64 encoded password
  ebsi-client-secret: "" # base64 encoded secret
  ebsi-user-password: "" # base64 encoded password