apiVersion: v1
kind: Secret
metadata:
  name: wallet-sealed-secret
  namespace: tenant-{{ .Values.global.tenantName | lower }}
data:
  postgres-password: "" # base64 encoded password
  ebsi-client-secret: "" # base64 encoded secret
  ebsi-user-password: "" # base64 encoded password