replicaCount: 1

image:
  repository: dome-adapter
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: dome-adapter.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
#   memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
  initialDelaySeconds: 40
  failureThreshold: 6
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
  initialDelaySeconds: 40
  failureThreshold: 6
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

secret:
  name: dome-adapter-secret

logging:
  level:
    es.altia.domeadapter: INFO

spring:
  mail:
    host: localhost
    port: 587
    username: ""
    password: ""
    existingSecret:
      enabled: false
      name: adapter-secret
      username: mail-username
      password: mail-password

app:
  logLevel:
    security: INFO

  db:
    host: localhost
    port: 5432
    name: dome_adapter
    schema: dome_adapter
    username: username
    password: password
    externalService: false
    ssl:
      enabled: false
      mode: disable
    existingSecret:
      enabled: false
      name: adapter-secret
      username: r2dbc-username
      password: r2dbc-password

  verifier-url: ""
  issuer-url: ""
  default-lang: en
  config-source: yaml

  mail:
    from: no-reply@example.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ""

adapter-identity:
  credential-subject-did-key: ""
  jwt-credential: ""
  crypto:
    private-key: ""
  existingSecret:
    enabled: false
    name: adapter-secret
    credentialSubjectDidKey: adapter-identity-credential-subject-did-key
    jwtCredential: adapter-identity-jwt-credential
    privateKey: adapter-identity-private-key

cors:
  external-allowed-origins: ""

retry:
  label-upload:
    certifier-email: ""
    marketplace-email: ""


dome-adapter-postgresql:
  # -- should the postgresql deployment be enabled
  enabled: true
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # ! Changing this parameter may cause the PVC to re-created and the data lost
  fullnameOverride: adapter-postgres
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # ! Changing this parameter may cause the PVC to re-created and the data lost
  nameOverride: adapter-postgres
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
  ## configuration of the postgres primary replica
  primary:
    # Configuration for Velero backup
    annotations:
      backup.velero.io/backup-volumes: data
    podAnnotations:
      backup.velero.io/backup-volumes: data
    ## provide db initialization
    initdb:
      ## provide scripts for initialization
      scripts:
        # -- create the database
        # -- !!Put the same database name and the same database schema
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE adapter;"
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 16.0.0-debian-11-r13
    pullPolicy: IfNotPresent