deployment:
  image:
    repository: in2kizuna/desmos
    tag: v0.5.0
    pullPolicy: Always
  logLevel: DEBUG
  dltAdapter:
    provider: digitelts
    internalDomain: http://dlt-adapter:8080
    externalDomain: http://dlt-adapter:8080
  eventSubscription:
    notificationEndpoint: http://desmos:8080/notifications/dlt
    eventTypes: catalog,product-offering,category
  broker:
    provider: scorpio
    internalDomain: http://scorpio:9090
    externalDomain: http://scorpio:9090
  ngsiSubscription:
    notificationEndpoint: http://desmos:8080/notifications/broker
    entityTypes: catalog,product-offering,category
  client:
    organizationId: did:web:my-marketplace-operator.org
db:
  host: postgresql-connector
  password: postgres
  username: postgres

service:
  port: 8080
  type: ClusterIP

fullnameOverride: "demos"
