apiVersion: v2
name: wallet-ui
description: A Helm chart for Kubernetes
type: application
version: 1.2.0
appVersion: "v1.2.0"

sources:
  - https://github.com/in2workspace/dome-wallet-ui

maintainers:
  - name: IN2 Team
    email: domesupport@in2.es