apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet-driving-application.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    {{- include "wallet-driving-application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "{{ .Values.service.port | default 4200}}"
      port: {{ .Values.service.port | default "4200"}}
      targetPort: 8088
  selector:
    {{- include "wallet-driving-application.selectorLabels" . | nindent 4 }}
