# as for the ingress nginx rewrite, see: https://kubernetes.github.io/ingress-nginx/examples/rewrite/

{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dome-issuer.fullname" . }}
  labels:
    {{- toYaml .Values.global.ingress.labels | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.global.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          # Backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-backend.service.name" . }}
                port:
                  number: 80
          - path: /vci
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-backend.service.name" . }}
                port:
                  number: 80
          - path: /backoffice
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-backend.service.name" . }}
                port:
                  number: 80
          - path: /oid4vci
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-backend.service.name" . }}
                port:
                  number: 80
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-backend.service.name" . }}
                port:
                  number: 80
          - path: /oauth/token
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-backend.service.name" . }}
                port:
                  number: 80
          #           Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dome-issuer-frontend.service.name" . }}
                port:
                  number: 80
  {{- if .Values.global.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: issuer-tls-secret
  {{- end }}
  {{- end }}
