{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "issuer.fullname" . }}
{{/*  labels:*/}}
{{/*    {{- include "issuer.labels" . | nindent 4 }}*/}}
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.className }}
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.global.ingress.annotations.sslRedirect }}"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ .Values.global.ingress.annotations.backendProtocol }}"
    {{- if .Values.global.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.annotations.clusterIssuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ include "issuer.url" . }}
      http:
        paths:
          # Backend
          - path: "/api"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "issuer-backend.service.name" . }}
                port:
                  number: 8080
          # Frontend
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "issuer-frontend.service.name" . }}
                port:
                  number: 80
  {{- if .Values.global.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ include "issuer.url" . }}
      secretName: issuer-tls-secret
  {{- end }}
{{- end }}
