{{- if not .Values.app.certificate.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: dss-certificate-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dss.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.app.certificate.password | b64enc }}
  {{- end }}
