apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desmos.fullname" . }}
  labels:
    {{- include "desmos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "desmos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
             {{ include "desmos.labels" . | nindent 8 }}
             {{- with .Values.deployment.additionalLabels }}
             {{- toYaml . | nindent 8 }}
             {{- end }}
         {{- if .Values.deployment.additionalAnnotations -}}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.enabled | quote }}
        prometheus.io/path: {{ .Values.prometheus.path }}
        prometheus.io/port: {{ .Values.prometheus.port }}
            {{- with .Values.deployment.additionalAnnotations }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: {{ include "desmos.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port}}
              protocol: TCP
            - name: http-health
              containerPort: {{ .Values.deployment.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          env:
            - name: SPRING_R2DBC_URL
              value: {{.Values.env.spring.r2dbc.url}}
            - name: SPRING_R2DBC_USERNAME
              value: {{.Values.env.spring.r2dbc.username}}
            - name: SPRING_R2DBC_PASSWORD
              value: {{.Values.env.spring.r2dbc.password}}
            - name: SPRING_FLYWAY_URL
              value: {{.Values.env.spring.flyway.url}}
            - name: LOGGING_LEVEL_ES_IN2_DESMOS
              value: {{.Values.env.logging.level.es.in2.desmos}}
            - name: OPENAPI_SERVER_URL
              value: {{.Values.env.openapi.server.url}}
            - name: OPENAPI_SERVER_DESCRIPTION
              value: {{.Values.env.openapi.server.description}}
            - name: OPENAPI_INFO_TITLE
              value: {{.Values.env.openapi.info.title}}
            - name: OPENAPI_INFO_DESCRIPTION
              value: {{.Values.env.openapi.info.description}}
            - name: OPENAPI_INFO_VERSION
              value: {{.Values.env.openapi.info.version}}
            - name: OPENAPI_INFO_TERMS_OF_SERVICE
              value: {{.Values.env.openapi.info.termsOfService}}
            - name: OPENAPI_INFO_LICENSE_NAME
              value: {{.Values.env.openapi.info.license.name}}
            - name: OPENAPI_INFO_LICENSE_URL
              value: {{.Values.env.openapi.info.license.url}}
            - name: OPENAPI_INFO_CONTACT_NAME
              value: {{.Values.env.openapi.info.contact.name}}
            - name: OPENAPI_INFO_CONTACT_URL
              value: {{.Values.env.openapi.info.contact.url}}
            - name: OPENAPI_INFO_CONTACT_EMAIL
              value: {{.Values.env.openapi.info.contact.email}}
            - name: CLIENT_ORGANIZATION_ID
              value: {{.Values.env.client.organizationId}}
            - name: BLOCKCHAIN_ADAPTER_INTERNAL_DOMAIN
              value: {{.Values.env.dltAdapter.internalDomain}}
            - name: BLOCKCHAIN_ADAPTER_EXTERNAL_DOMAIN
              value: {{.Values.env.dltAdapter.externalDomain}}
            - name: BLOCKCHAIN_ADAPTER_PROVIDER
              value: {{.Values.env.dltAdapter.provider}}
            - name: DLT_ADAPTER_PATHS_PUBLISH
              value: {{.Values.env.dltAdapter.paths.publication}}
            - name: DLT_ADAPTER_PATHS_SUBSCRIBE
              value: {{.Values.env.dltAdapter.paths.subscription}}
            - name: DLT_ADAPTER_PATHS_EVENTS
              value: {{.Values.env.dltAdapter.paths.events}}
            - name: BLOCKCHAIN_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{.Values.env.blockchain.subscription.notificationEndpoint}}
            - name: BLOCKCHAIN_SUBSCRIPTION_EVENT_TYPES
              value: {{.Values.env.blockchain.subscription.eventTypes}}
            - name: BROKER_PROVIDER
              value: {{.Values.env.broker.provider}}
            - name: BROKER_EXTERNAL_DOMAIN
              value: {{.Values.env.broker.externalDomain}}
            - name: BROKER_INTERNAL_DOMAIN
              value: {{.Values.env.broker.internalDomain}}
            - name: NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{.Values.env.ngsiSubscription.notificationEndpoint}}
            - name: NGSI_SUBSCRIPTION_ENTITY_TYPES
              value: {{.Values.env.ngsiSubscription.entityTypes}}
          resources:
                {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deployment.affinity }}
      affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.deployment.tolerations }}
      tolerations:
             {{- toYaml . | nindent 8 }}
          {{- end }}
      restartPolicy: Always