apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desmos.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "desmos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "desmos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "desmos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "desmos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-external-services
          image: curlimages/curl
          command:
            - sh
            - -c
            - >
              echo "Checking availability for: {{ .Values.app.broker.internalDomain }}/q/health";
              echo "Checking availability for: {{ .Values.app.dltAdapter.internalDomain }}/health";
              response1=$(curl -si {{ .Values.app.broker.internalDomain }}/q/health);
              response2=$(curl -si {{ .Values.app.dltAdapter.internalDomain }}/health);
              until echo "$response1" | grep -q "HTTP/1.[01] 200 OK" && echo "$response2" | grep -q "HTTP/1.[01] 200 OK"; do
                echo "Waiting for external services to be available at {{ .Values.app.broker.internalDomain }}/q/health and {{ .Values.app.dltAdapter.internalDomain }}/health...";
                echo "Response from {{ .Values.app.broker.internalDomain }}/q/health:";
                echo "$response1";
                echo "Response from {{ .Values.app.dltAdapter.internalDomain }}/health:";
                echo "$response2";
                sleep 10;
                response1=$(curl -si {{ .Values.app.broker.internalDomain }}/q/health);
                response2=$(curl -si {{ .Values.app.dltAdapter.internalDomain }}/health);
              done;
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.app.profile}}
            - name: LOGGING_LEVEL_ROOT
              value: {{.Values.app.logLevel}}
            - name: SERVER_PORT
              value: {{ quote .Values.app.internalServerPort}}
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://{{ .Values.db.host }}{{ if not .Values.db.externalService }}:{{ .Values.db.port }}{{ end }}/{{ .Values.db.name }}"
            - name: SPRING_R2DBC_USERNAME
              value: {{.Values.db.username}}
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "desmos.secretName" . }}
                  key: {{ include "desmos.passwordKey" . }}
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}{{ if not .Values.db.externalService }}:{{ .Values.db.port }}{{ end }}/{{ .Values.db.name }}"
            - name: OPERATOR_ORGANIZATION_IDENTIFIER
              value: {{.Values.app.operator.organizationIdentifier}}
            - name: BROKER_PROVIDER
              value: {{.Values.app.broker.provider}}
            - name: BROKER_EXTERNAL_DOMAIN
              value: {{.Values.app.broker.externalDomain}}
            - name: BROKER_INTERNAL_DOMAIN
              value: {{.Values.app.broker.internalDomain}}
            - name: NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: "http://{{.Chart.Name}}:{{.Values.app.internalServerPort}}{{.Values.app.ngsiSubscription.notificationEndpoint}}"
            - name: NGSI_SUBSCRIPTION_ENTITY_TYPES
              value: {{.Values.app.ngsiSubscription.entityTypes}}
            - name: DLT_ADAPTER_PROVIDER
              value: {{.Values.app.dltAdapter.provider}}
            - name: DLT_ADAPTER_INTERNAL_DOMAIN
              value: {{.Values.app.dltAdapter.internalDomain}}
            - name: DLT_ADAPTER_EXTERNAL_DOMAIN
              value: {{.Values.app.dltAdapter.externalDomain}}
            - name: TX_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: "http://{{.Chart.Name}}:{{.Values.app.internalServerPort}}{{.Values.app.txSubscription.notificationEndpoint}}"
            - name: TX_SUBSCRIPTION_ENTITY_TYPES
              value: {{.Values.app.txSubscription.entityTypes}}
