apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desmos.fullname" . }}
  labels:
    {{- include "desmos.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desmos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
            {{ include "desmos.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: LOGGING_LEVEL_ROOT
              value: {{.Values.deployment.logLevel}}
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://{{ .Values.db.host }}:5432/demos"
            - name: SPRING_R2DBC_USERNAME
              value: {{.Values.db.username}}
            - name: SPRING_R2DBC_PASSWORD
              value: {{.Values.db.password}}
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}:5432/desmos"
            - name: SPRING_FLYWAY_USERNAME
              value: {{ .Values.db.username }}
            - name: DLT_ADAPTER_PROVIDER
              value: {{.Values.deployment.dltAdapter.provider}}
            - name: DLT_ADAPTER_INTERNAL_DOMAIN
              value: {{.Values.deployment.dltAdapter.internalDomain}}
            - name: DLT_ADAPTER_EXTERNAL_DOMAIN
              value: {{.Values.deployment.dltAdapter.externalDomain}}
            - name: EVENT_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{.Values.deployment.eventSubscription.notificationEndpoint}}
            - name: EVENT_SUBSCRIPTION_EVENT_TYPES
              value: {{.Values.deployment.eventSubscription.eventTypes}}
            - name: BROKER_PROVIDER
              value: {{.Values.deployment.broker.provider}}
            - name: BROKER_EXTERNAL_DOMAIN
              value: {{.Values.deployment.broker.externalDomain}}
            - name: BROKER_INTERNAL_DOMAIN
              value: {{.Values.deployment.broker.internalDomain}}
            - name: NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{.Values.deployment.ngsiSubscription.notificationEndpoint}}
            - name: NGSI_SUBSCRIPTION_ENTITY_TYPES
              value: {{.Values.deployment.ngsiSubscription.entityTypes}}
            - name: CLIENT_ORGANIZATION_ID
              value: {{.Values.deployment.client.organizationId}}
          ports:
            - containerPort: {{ .Values.service.port}}
              name: http
              protocol: TCP
