apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desmos.fullname" . }}
  labels:
    {{- include "desmos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
    {{- end }}
  selector:
    matchLabels:
        {{- include "desmos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "desmos.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
              {{- toYaml . | nindent 8 }}
            {{- end }}
      serviceAccountName: {{ include "desmos.serviceAccountName" . }}
      securityContext:
              {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http-health
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: LOGGING_LEVEL_ROOT
              value: {{.Values.app.logLevel}}
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://{{ .Values.db.host }}:5432/mktdb"
            - name: SPRING_R2DBC_USERNAME
              value: {{.Values.db.username}}
            - name: SPRING_R2DBC_PASSWORD
              value: {{.Values.db.password}}
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}:5432/mktdb"
            - name: SPRING_FLYWAY_USERNAME
              value: {{ .Values.db.username }}
            - name: DLT_ADAPTER_PROVIDER
              value: {{.Values.app.dltAdapter.provider}}
            - name: DLT_ADAPTER_INTERNAL_DOMAIN
              value: {{.Values.app.dltAdapter.internalDomain}}
            - name: DLT_ADAPTER_EXTERNAL_DOMAIN
              value: {{.Values.app.dltAdapter.externalDomain}}
            - name: EVENT_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{.Values.app.eventSubscription.notificationEndpoint}}
            - name: EVENT_SUBSCRIPTION_EVENT_TYPES
              value: {{.Values.app.eventSubscription.eventTypes}}
            - name: BROKER_PROVIDER
              value: {{.Values.app.broker.provider}}
            - name: BROKER_EXTERNAL_DOMAIN
              value: {{.Values.app.broker.externalDomain}}
            - name: BROKER_INTERNAL_DOMAIN
              value: {{.Values.app.broker.internalDomain}}
            - name: NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{.Values.app.ngsiSubscription.notificationEndpoint}}
            - name: NGSI_SUBSCRIPTION_ENTITY_TYPES
              value: {{.Values.app.ngsiSubscription.entityTypes}}
            - name: CLIENT_ORGANIZATION_ID
              value: {{.Values.app.client.organizationId}}
