{{- if not .Values.app.learCredentialMachineInBase64.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: desmos-lear-credential-machine-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "desmos.labels" . | nindent 4 }}
type: Opaque
data:
  learCredentialMachine: {{ .Values.app.learCredentialMachineInBase64.value | b64enc }}
  {{- end }}