{{- if not .Values.app.learCredentialMachine.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: desmos-private-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "desmos.labels" . | nindent 4 }}
type: Opaque
data:
  learCredentialMachine: {{ .Values.app.learCredentialMachine.value | b64enc }}
  {{- end }}