{{- if not .Values.app.privateKey.existingSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: desmos-private-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "desmos.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.app.privateKey.value | b64enc }}
  {{- end }}