{{- if not (or .Values.app.db.existingSecret.enabled .Values.app.security.serviceIdentity.existingSecret.enabled .Values.app.security.keycloak.client.existingSecret.enabled .Values.app.mail.existingSecret.enabled .Values.app.remoteSignature.existingSecret.enabled .Values.app.remoteSignature.defaultSigner.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: issuer-backend-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "issuer-backend.labels" . | nindent 4 }}
type: Opaque
data:
  # database
  {{- if not .Values.app.db.existingSecret.enabled }}
  postgres-password: {{ .Values.app.db.password | b64enc }}
  {{- end }}
  # service-identity
  {{- if not .Values.app.security.serviceIdentity.existingSecret.enabled }}
  private-key: {{ .Values.app.security.serviceIdentity.privateKey | b64enc }}
  did-key: {{ .Values.app.security.serviceIdentity.didKey | b64enc }}
  vc: {{ .Values.app.security.serviceIdentity.verifiableCredential | b64enc }}
  {{- end }}
  # keycloak
  {{- if not .Values.app.security.keycloak.client.existingSecret.enabled }}
  keycloak-client-secret: {{ .Values.app.security.keycloak.client.clientSecret | b64enc }}
  keycloak-password: {{ .Values.app.security.keycloak.client.password | b64enc }}
  {{- end }}
  # email
  {{- if not .Values.app.mail.existingSecret.enabled }}
  mail-username: {{ .Values.app.mail.username | b64enc }}
  mail-password: {{ .Values.app.mail.password | b64enc }}
  {{- end }}
  # dss-signature-service
  {{- if not .Values.app.remoteSignature.existingSecret.enabled }}
  client-id: {{ .Values.app.remoteSignature.credentialId | b64enc }}
  client-secret: {{ .Values.app.remoteSignature.clientSecret | b64enc }}
  credential-id: {{ .Values.app.remoteSignature.credentialId | b64enc }}
  credential-password: {{ .Values.app.remoteSignature.credentialPassword | b64enc }}
  {{- end }}
  # todo: estos secretos quedan deprecados porque se generan en el código
  {{- if not .Values.app.remoteSignature.defaultSigner.existingSecret.enabled }}
  signer-common-name: {{ .Values.app.remoteSignature.defaultSigner.commonName | b64enc }}
  signer-serial-number: {{ .Values.app.remoteSignature.defaultSigner.serialNumber | b64enc }}
  signer-email: {{ .Values.app.remoteSignature.defaultSigner.email | b64enc }}
  signer-organization: {{ .Values.app.remoteSignature.defaultSigner.organization | b64enc }}
  signer-organization-identifier: {{ .Values.app.remoteSignature.defaultSigner.organizationIdentifier | b64enc }}
  signer-country: {{ .Values.app.remoteSignature.defaultSigner.country | b64enc }}
  {{- end }}
{{- end }}
