apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "issuer-ui.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "issuer-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "issuer-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "issuer-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "issuer-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.internalServerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.app.internalServerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: LOGIN_URL
              value: "{{ .Values.app.loginUrl.scheme }}://{{ .Values.app.loginUrl.host }}{{ if not .Values.app.loginUrl.externalService }}:{{ .Values.app.loginUrl.internalPort }}{{ end }}{{ .Values.app.loginUrl.path }}"
            - name: LOGIN_URL
              value: "{{ .Values.app.loginUrl.scheme }}://{{ .Values.app.loginUrl.host }}{{ if not .Values.app.loginUrl.externalService }}:{{ .Values.app.loginUrl.internalPort }}{{ end }}{{ .Values.app.loginUrl.path }}"
            - name: CLIENT_ID
              value: {{ .Values.app.clientId }}
            - name: SCOPE
              value: {{ .Values.app.scope }}
            - name: GRANT_TYPE
              value: {{ .Values.app.grantType }}
            - name: BASE_URL
              value: "{{ .Values.app.baseUrl.scheme }}://{{ .Values.app.baseUrl.host }}{{ if not .Values.app.baseUrl.externalService }}:{{ .Values.app.baseUrl.internalPort }}{{ end }}{{ .Values.app.baseUrl.path }}"
            - name: WALLET_URL
              value: "{{ .Values.app.walletUrl.scheme }}://{{ .Values.app.walletUrl.host }}{{ if not .Values.app.walletUrl.externalService }}:{{ .Values.app.walletUrl.internalPort }}{{ end }}{{ .Values.app.walletUrl.path }}"
            - name: PROCEDURES
              value: {{ .Values.app.procedures }}
            - name: SAVE_CREDENTIAL
              value: {{ .Values.app.saveCredential }}
            - name: CREDENTIAL_OFFER_URL
              value: {{ .Values.app.credentialOfferUrl }}
            - name: NOTIFICATION
              value: {{ .Values.app.notification }}