apiVersion: v1
kind: Service
metadata:
  name: {{ include "issuer-ui.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "issuer-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.app.internalServerPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "issuer-ui.selectorLabels" . | nindent 4 }}