{{- if not .Values.app.backend.security.serviceIdentity.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: verifier-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-verifier.labels" . | nindent 4 }}
type: Opaque
data:
  private-key: {{ .Values.app.backend.security.serviceIdentity.privateKey  | b64enc }}
  verifiable-credential: {{ .Values.app.backend.security.serviceIdentity.verifiableCredential | b64enc }}
{{- end }}