apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dss.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dss.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dss.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dss.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            # fixme: Uso dev porque el perfil de PRD no está definido
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            # Constants
            - name: SERVER_PORT
              value: "8050"
            - name: APP_CONFIG_SOURCE_NAME
              value: "yaml"
              # todo: redefinir a internalURL
            - name: AUTH_SERVER_INTERNAL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-dss-cm
                  key: KEYCLOAK_INTERNAL_URL
            - name: AUTH_SERVER_EXTERNAL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-dss-cm
                  key: KEYCLOAK_EXTERNAL_URL
            - name: AUTH_SERVER_REALM
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-dss-cm
                  key: KEYCLOAK_REALM_PATH
            # CERTIFICATE
            - name: APP_PROPERTIES_CERTIFICATE_KEY
              value: {{ .Values.app.certificate.name }}
            - name: CERTIFICATE_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dss.certificateSecretName" . }}
                  key: {{ include "dss.certificateSecretKey" . }}
            # VAULT
            - name: VAULT_PROVIDER_NAME
              value: {{ .Values.app.vault.provider }}
            - name: HASHICORP_VAULT_HOST
              value: {{ .Values.app.vault.host }}
            - name: HASHICORP_VAULT_SCHEME
              value: {{ .Values.app.vault.scheme }}
            - name: HASHICORP_VAULT_PORT
              value: {{ quote .Values.app.vault.port }}
            - name: HASHICORP_VAULT_PATH
              value: {{ .Values.app.vault.path }}
            - name: HASHICORP_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dss.vaultSecretName" . }}
                  key: {{ include "dss.vaultSecretKey" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            { - toYaml . | nindent 12 } }
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
