

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # todo
  name: {{ include "dome-wallet.fullname" . }}-frontend
  labels:
    {{- toYaml .Values.ingress.labels | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- with .Values.ingress.frontend.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ index .Values "dome-wallet-frontend" "fullnameOverride" }}
                port:
                  number: 80
  {{- if .Values.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: wallet-tls-secret
  {{- end }}
{{- end }}