# as for the ingress nginx rewrite, see: https://kubernetes.github.io/ingress-nginx/examples/rewrite/

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dome-wallet.fullname" . }}
  labels:
    {{- toYaml .Values.ingress.labels | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Backend
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ index .Values "dome-wallet-backend" "fullnameOverride" }}
                port:
                  number: 80
#           Frontend
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ index .Values "dome-wallet-frontend" "fullnameOverride" }}
                port:
                  number: 80
  {{- if .Values.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: wallet-tls-secret
  {{- end }}
  {{- end }}
