{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dome-wallet.fullname" . }}
  labels: {{ .Values.ingress.labels }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ .Values.ingress.backendProtocol }}"
    {{- if .Values.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Backend
          - path: {{ index .Values "dome-wallet-backend" "app" "basePath" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ index .Values "dome-wallet-backend" "fullnameOverride" }}
                port:
                  number: 80
          # Frontend
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ index .Values "dome-wallet-frontend" "fullnameOverride" }}
                port:
                  number: 80
  {{- if .Values.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: wallet-tls-secret
  {{- end }}
  {{- end }}