locals {
  aurora            = "${var.project_name}-${var.environment}-aur-${var.region_code}"
  s3                = "${var.project_name}-${var.environment}-s3-${var.region_code}"
  ecs               = "${var.project_name}-${var.environment}-ecs-${var.region_code}"
  ecr               = "${var.project_name}-${var.environment}-ecr-${var.region_code}"
  apprunner         = "${var.project_name}-${var.environment}-app-${var.region_code}"
  lambda            = "${var.project_name}-${var.environment}-lam-${var.region_code}"
  eventbridge       = "${var.project_name}-${var.environment}-evn-${var.region_code}"
  stepfunctions     = "${var.project_name}-${var.environment}-sfn-${var.region_code}"
  apigateway        = "${var.project_name}-${var.environment}-api-${var.region_code}"
  cloudfront        = "${var.project_name}-${var.environment}-cdn-${var.region_code}"
  vpc               = "${var.project_name}-${var.environment}-vpc-${var.region_code}"
  elb               = "${var.project_name}-${var.environment}-lbg-${var.region_code}"
  elb_target_group  = "${var.project_name}-${var.environment}-ltg-${var.region_code}"
  rds               = "${var.project_name}-${var.environment}-rds-${var.region_code}"
  dynamodb          = "${var.project_name}-${var.environment}-ddb-${var.region_code}"
  cwa               = "${var.project_name}-${var.environment}-cwa-${var.region_code}"
  secrets           = "${var.project_name}-${var.environment}-scr-${var.region_code}"
  parameterstore    = "${var.project_name}-${var.environment}-pms-${var.region_code}"
  efs               = "${var.project_name}-${var.environment}-efs-${var.region_code}"
  subnetgroup       = "${var.project_name}-${var.environment}-sbg-${var.region_code}"
  securitygroup     = "${var.project_name}-${var.environment}-scg-${var.region_code}"
  vpc_connector     = "${var.project_name}-${var.environment}-vcn-${var.region_code}"
  service_discovery = "${var.project_name}-${var.environment}-sdc-${var.region_code}"
  vpclink           = "${var.project_name}-${var.environment}-vpl-${var.region_code}"
  iam_role          = "${var.project_name}-${var.environment}-rol-${var.region_code}"
  elastic_cache     = "${var.project_name}-${var.environment}-ech-${var.region_code}"
  route53           = "${var.project_name}-${var.environment}-r53-${var.region_code}"
  route53_resolver  = "${var.project_name}-${var.environment}-r53r-${var.region_code}"
  rds_postgres     = "${var.project_name}-${var.environment}-psql-${var.region_code}"
  waf              = "${var.project_name}-${var.environment}-waf-${var.region_code}"
  ses_domain       = "mail-${var.environment}.${var.tenant_name}.${var.domain_name}"
  app_domain       = "${var.environment}.${var.tenant_name}.${var.domain_name}"

  # This is the 'prefix' of the URI of all the ECR repositories created in the same account and region. This can be used in conjunction with the repo name and tag to compose the full URI.
  ecr_prefix = "${data.aws_caller_identity.current.account_id}.dkr.ecr.${data.aws_region.current.name}.amazonaws.com"
}
