{{- if or
    (not .Values.app.db.existingSecret.enabled)
    (not .Values.app.remoteSignature.existingSecret.enabled)
    (not .Values.app.defaultSigner.existingSecret.enabled)
    (not .Values.app.authServer.client.existingSecret.enabled)
    (not .Values.app.mail.existingSecret.enabled)
    (not .Values.app.issuerIdentity.existingSecret.enabled)
    (not .Values.app.vault.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dome-issuer-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-issuer-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.app.db.existingSecret.enabled }}
  postgres-password: {{ .Values.app.db.password | b64enc }}
  {{- end }}
  {{- if not .Values.app.remoteSignature.existingSecret.enabled }}
  remote-signature-client-id: {{ .Values.app.remoteSignature.clientId | b64enc }}
  remote-signature-client-secret: {{ .Values.app.remoteSignature.clientSecret | b64enc }}
  remote-signature-credential-id: {{ .Values.app.remoteSignature.credentialId | b64enc }}
  remote-signature-credential-password: {{ .Values.app.remoteSignature.credentialPassword | b64enc }}
  {{- end }}
  {{- if not .Values.app.defaultSigner.existingSecret.enabled }}
  default-signer-common-name: {{ .Values.app.defaultSigner.commonName | b64enc }}
  default-signer-country: {{ .Values.app.defaultSigner.country | b64enc }}
  default-signer-email: {{ .Values.app.defaultSigner.email | b64enc }}
  default-signer-organization: {{ .Values.app.defaultSigner.organization | b64enc }}
  default-signer-organization-identifier: {{ .Values.app.defaultSigner.organizationIdentifier | b64enc }}
  default-signer-serial-number: {{ .Values.app.defaultSigner.serialNumber | b64enc }}
  {{- end }}
  {{- if not .Values.app.authServer.client.existingSecret.enabled }}
  auth-server-password: {{ .Values.app.authServer.client.password | b64enc }}
  {{- end }}
  {{- if not .Values.app.mail.existingSecret.enabled }}
  mail-username: {{ .Values.app.mail.username | b64enc }}
  mail-password: {{ .Values.app.mail.password | b64enc }}
  {{- end }}
  {{- if not .Values.app.issuerIdentity.existingSecret.enabled }}
  issuer-identity-vc: {{ .Values.app.issuerIdentity.jwtCredential | b64enc }}
  issuer-identity-private-key: {{ .Values.app.issuerIdentity.privateKey | b64enc }}
  issuer-identity-credential-did-key: {{ .Values.app.issuerIdentity.credentialDidKey | b64enc }}
  {{- end }}
  {{- if not .Values.app.vault.existingSecret.enabled }}
  vault-token: {{ .Values.app.vault.token | b64enc }}
  {{- end }}
{{- end }}