{{- if or
    (not .Values.app.db.existingSecret.enabled)
    (not .Values.app.keycloak.admin.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dome-issuer-keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "dome-issuer-keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.app.db.existingSecret.enabled }}
  keycloak-db-password: {{ .Values.app.db.password | b64enc }}
  {{- end }}

  {{- if not .Values.app.keycloak.admin.existingSecret.enabled }}
  keycloak-password: {{ .Values.app.keycloak.admin.password | b64enc }}
  {{- end }}
{{- end }}