name: Deploy Helm Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  package-and-publish:
    name: Package and Publish Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Create Output Directory
        run: mkdir -p helm-packages

      - name: Package Helm Charts
        run: |
          CHARTS=(
            desmos
            issuer-api
            dome-issuer-keycloak
            issuer-ui
            wallet-api
            dome-wallet-keycloak
            dome-wallet-ui
            wallet
            issuer
            dome-dss
            access-node
            verifier-api
            portal-ui
            keycloak
          )

          for CHART in "${CHARTS[@]}"; do
            if [ -d "charts/$CHART" ]; then
              helm dependency build "charts/$CHART"
              helm package "charts/$CHART" --destination helm-packages
            fi
          done

      - name: Upload Helm Repository Index
        run: helm repo index helm-packages --url https://in2workspace.github.io/helm-charts

      - name: Commit and Push Packages to Main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git checkout main
          git pull --rebase origin main
          
          cp -r helm-packages/*.tgz .
          helm repo index . --url https://in2workspace.github.io/helm-charts
          
          git add *.tgz
          git add index.yaml
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          git commit -m "Update Helm charts"
          git push https://your-github-username:${GH_PAT}@github.com/${{ github.repository }}.git main

